"""Phase 15 fragment-level partial replay.

The pre-phase replay planner returned either a full plan (all bullets
for a matched topic) or None. This module replaces that with
fragment-level matching: each procedural bullet is evaluated
independently and the matcher returns an ordered list of
`(step_index, replay_action | None)` pairs. Bullets whose stored
`value` was populated at capture time produce `requires_model_value=True`
fragments so the coordinate and action type replay verbatim but the
dynamic value is regenerated by the model loop.

The runner interleaves fragments with model calls: if the fragment list
has an Action at the current step index, it dispatches that Action
directly; otherwise it drops into the full model substeps.

Phase 11 replay confidence scoring applies per fragment. Each fragment
below `CUTIEE_REPLAY_FRAGMENT_CONFIDENCE` routes through the approval
gate before execution.
"""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Any

from ..harness.state import Action, ActionType, RiskLevel
from .bullet import Bullet
from .embeddings import cosineSimilarity, embedTexts
from .pipeline import ACEPipeline

logger = logging.getLogger("cutiee.fragment_replay")


@dataclass
class ReplayFragment:
    step_index: int
    action: Action
    confidence: float
    requires_model_value: bool = False
    bullet_id: str = ""
    reason: str = ""


@dataclass
class FragmentPlan:
    fragments: list[ReplayFragment] = field(default_factory = list)

    def fragmentForStep(self, stepIndex: int) -> ReplayFragment | None:
        for fragment in self.fragments:
            if fragment.step_index == stepIndex:
                return fragment
        return None

    def replayCount(self) -> int:
        return len(self.fragments)

    def valueVariantCount(self) -> int:
        return sum(1 for fragment in self.fragments if fragment.requires_model_value)


def findReplayFragments(
    *,
    pipeline: ACEPipeline,
    taskDescription: str,
    userId: str,
    currentDomain: str = "",
    fragmentConfidenceThreshold: float = 0.80,
) -> FragmentPlan:
    """Build a fragment-level replay plan for the upcoming task.

    Retrieves procedural bullets relevant to the task description,
    scores each one individually, translates qualifying bullets into
    canonical `Action` instances, and returns them in step order.
    """
    del userId  # ACEMemory inside the pipeline is already user-scoped.

    candidates = pipeline.retrieveRelevantBullets(taskDescription, k = 24)
    procedural = [b for b in candidates if b.memory_type == "procedural"]
    if not procedural:
        return FragmentPlan()

    queryEmbedding = embedTexts(
        [taskDescription],
        useHashFallback = pipeline.memory.useHashEmbedding,
    )[0]

    fragments: list[ReplayFragment] = []
    seenSteps: set[int] = set()
    for bullet in sorted(procedural, key = _stepIndexFromContent):
        stepIndex = _stepIndexFromContent(bullet)
        if stepIndex in seenSteps:
            continue
        seenSteps.add(stepIndex)

        action, requiresModelValue = _fragmentActionFromBullet(bullet)
        if action is None:
            continue

        confidence = _scoreFragment(
            bullet = bullet,
            queryEmbedding = queryEmbedding,
            currentDomain = currentDomain,
        )
        if confidence < fragmentConfidenceThreshold:
            logger.debug(
                "fragment rejected: bullet=%s step=%d confidence=%.2f",
                bullet.id, stepIndex, confidence,
            )
            continue

        fragments.append(ReplayFragment(
            step_index = stepIndex,
            action = action,
            confidence = confidence,
            requires_model_value = requiresModelValue,
            bullet_id = bullet.id,
            reason = f"bullet:{bullet.id[:8]}",
        ))

    return FragmentPlan(fragments = fragments)


def _scoreFragment(
    *,
    bullet: Bullet,
    queryEmbedding: list[float],
    currentDomain: str,
) -> float:
    """Combine description similarity, risk, and domain match into a score.

    Plan Phase 11 prescribes three components:
      a) per-step risk level: high-risk fragments receive a confidence
         penalty so they must clear a higher bar to fire.
      b) embedding similarity between the new task description and
         the bullet content.
      c) domain match bonus when the bullet's domain tag matches the
         current run's domain.
    """
    similarity = cosineSimilarity(queryEmbedding, bullet.embedding) if bullet.embedding else 0.0
    similarity = max(0.0, similarity)

    domainBonus = 0.0
    if currentDomain:
        for tag in bullet.tags:
            if tag.startswith("domain:") and tag.split(":", 1)[1] == currentDomain:
                domainBonus = 0.10
                break

    riskPenalty = 0.15 if "risk:high" in bullet.tags else 0.0
    return max(0.0, min(1.0, 0.70 * similarity + domainBonus + 0.10 - riskPenalty))


def _fragmentActionFromBullet(bullet: Bullet) -> tuple[Action | None, bool]:
    """Fragment-replay reconstruction. Flags value-variant bullets.

    Thin wrapper over `bullet_reconstruct.actionFromBullet` so the
    shared parsing lives in one place. Sets
    `modelVariantOnNonEmptyValue=True` so any bullet whose stored value
    is non-empty or redacted replays its coordinate verbatim but emits
    with `value=None` plus `requires_model_value=True`.
    """
    from .bullet_reconstruct import actionFromBullet
    return actionFromBullet(
        bullet,
        modelVariantOnNonEmptyValue = True,
        reasoningPrefix = "fragment_replay",
        modelUsed = "replay",
    )


from .text_utils import stepIndexFromContent as _stepIndexBase  # noqa: E402


def _stepIndexFromContent(bullet: Bullet) -> int:
    return _stepIndexBase(bullet.content)
