"""Generate placeholder PNGs for `docs/screenshots/`.

Used when a live capture (`scripts/capture_screenshots.py`) is not
practical, e.g. during CI builds or before the dev server is up. Each
placeholder image is a 1280x800 rectangle in CUTIEE's slate-blue
palette with a label naming the page it represents and a short note
that real screenshots live in the script-driven capture flow.

Usage:
    uv run python scripts/make_placeholder_screenshots.py
"""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = REPO_ROOT / "docs" / "screenshots"

PALETTE_BG = (24, 28, 48)
PALETTE_PANEL = (44, 54, 88)
PALETTE_PRIMARY = (108, 134, 192)
PALETTE_ACCENT = (207, 108, 192)
PALETTE_TEXT = (235, 235, 245)
PALETTE_MUTED = (170, 178, 200)

PAGES: list[tuple[str, str, str]] = [
    ("01-landing.png", "Landing page", "/ public marketing surface"),
    ("02-login.png", "Sign in", "/accounts/login/ Google OAuth + email"),
    ("03-tasks.png", "Tasks workspace", "/tasks/ submission form, live banner, recent tasks"),
    ("04-detail.png", "Task detail", "/tasks/<id>/ HTMX progress, audit trail, replay status"),
    (
        "05-dashboard.png",
        "Cost dashboard",
        "/tasks/dashboard/ Chart.js timeseries + tier doughnut + CSV download",
    ),
]


def loadFont(size: int) -> ImageFont.ImageFont:
    candidates = [
        "/System/Library/Fonts/SFNS.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
        "/Library/Fonts/Arial.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    ]
    for path in candidates:
        if Path(path).exists():
            try:
                return ImageFont.truetype(path, size)
            except OSError:
                continue
    return ImageFont.load_default()


def drawPlaceholder(filename: str, title: str, route: str) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    width, height = 1280, 800
    img = Image.new("RGB", (width, height), color=PALETTE_BG)
    draw = ImageDraw.Draw(img)

    panelMargin = 64
    draw.rounded_rectangle(
        (panelMargin, panelMargin, width - panelMargin, height - panelMargin),
        radius=24,
        fill=PALETTE_PANEL,
    )

    bandHeight = 6
    draw.rectangle(
        (panelMargin, panelMargin, width - panelMargin, panelMargin + bandHeight),
        fill=PALETTE_PRIMARY,
    )

    titleFont = loadFont(58)
    routeFont = loadFont(28)
    bodyFont = loadFont(22)
    smallFont = loadFont(18)

    draw.text((panelMargin + 56, panelMargin + 64), "CUTIEE", fill=PALETTE_ACCENT, font=routeFont)
    draw.text((panelMargin + 56, panelMargin + 104), title, fill=PALETTE_TEXT, font=titleFont)
    draw.text(
        (panelMargin + 56, panelMargin + 196),
        route,
        fill=PALETTE_MUTED,
        font=bodyFont,
    )

    notes = [
        "Placeholder image generated by scripts/make_placeholder_screenshots.py.",
        "Replace with a live capture by running scripts/capture_screenshots.py",
        "against a local CUTIEE dev server (CUTIEE_ENV=local + Neo4j up).",
        "",
        "See README_AI.md and SPEC.md for the live page contents this represents.",
    ]
    yCursor = panelMargin + 280
    for line in notes:
        draw.text((panelMargin + 56, yCursor), line, fill=PALETTE_MUTED, font=smallFont)
        yCursor += 32

    footerY = height - panelMargin - 60
    draw.text(
        (panelMargin + 56, footerY),
        "INFO490 A10 submission",
        fill=PALETTE_PRIMARY,
        font=smallFont,
    )

    img.save(OUT_DIR / filename, format="PNG", optimize=True)


def main() -> int:
    for filename, title, route in PAGES:
        drawPlaceholder(filename, title, route)
        print(f"wrote docs/screenshots/{filename}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
